### ISSUE TITLE
Error downloading L2A .SAFE products from start of 2017

### ISSUE THREAD

**Issue by jirikadlec2** [sentinel-hub/sentinelhub-py#116] opened 2020-03-05 16:05 UTC
When I try to use sentinelhub.aws to download L2A .SAFE products from January-April 2017, sentinelhub.aws fails with an error.

Example command:
`sentinelhub.aws --product S2A_MSIL2A_20170414T101021_N0001_R022_T33UUQ_20190508T121145 --l2a`

Error message:
`Traceback (most recent call last): File "/usr/local/bin/sentinelhub.aws", line 8, in sys.exit(aws()) File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/usr/local/lib/python3.6/dist-packages/sentinelhub/commands.py", line 67, in aws download_safe_format(product_id=product, folder=folder, redownload=redownload, bands=band_list) File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 942, in download_safe_format AwsProductRequest(product_id, data_folder=folder, bands=bands, safe_format=True) File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 811, in __init__ super().__init__(**kwargs) File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 767, in __init__ super().__init__(AwsDownloadClient, **kwargs) File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 52, in __init__ self.create_request() File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 821, in create_request self.download_list, self.folder_list = self.aws_service.get_requests() File "/usr/local/lib/python3.6/dist-packages/sentinelhub/aws_safe.py", line 23, in get_requests safe = self.get_safe_struct() File "/usr/local/lib/python3.6/dist-packages/sentinelhub/aws_safe.py", line 64, in get_safe_struct metafiles=self.metafiles, data_source=self.data_source).get_safe_struct() File "/usr/local/lib/python3.6/dist-packages/sentinelhub/aws_safe.py", line 165, in __init__ self.tile_id = self.get_tile_id() File "/usr/local/lib/python3.6/dist-packages/sentinelhub/aws_safe.py", line 265, in get_tile_id tile_id = tree[0].find(tile_id_tag).text AttributeError: 'NoneType' object has no attribute 'text' `

I have noticed that the product name is S2A_MSIL2A_20170414T101021_N0001_R022_T33UUQ_20190508T121145 - original L1C image was acquired on 2017-04-14 but it was reprocessed to L2A much later, in 2019-05-08.

**Comment by gmilcinski** [comment] 2020-03-05 16:12
Not sure what is causing the error, but perhaps useful info. 
This product was processed by us, probably due to original being corrupt (and no longer available on SciHub in 2019). It was processed with Sen2Cor 02.08 so this product is not exactly the same as the original product.

**Comment by AleksMat** [comment] 2020-03-05 17:26
Hi @jirikadlec2,

I checked the issue. As @gmilcinski said the problem is that this tile has been re-processed by us and this introduced a new special case of the naming convention which is not supported in `sentinelhub-py`.

What happens is that `sentinelhub-py` first downloads [this json](https://roda.sentinel-hub.com/sentinel-s2-l2a/products/2017/4/14/S2A_MSIL2A_20170414T101021_N0001_R022_T33UUQ_20190508T121145/productInfo.json) where it finds out that the baseline processing number is `00.01`. Then it downloads [this xml](https://roda.sentinel-hub.com/sentinel-s2-l2a/tiles/33/U/UQ/2017/4/14/0/metadata.xml) where looks for a tag `'TILE_ID_2A'` in order to reconstruct an original L2A tile ID. However, the xml doesn't contain the tag and therefore the process fails.

As far as I can see a few additional checks that would have to be added in the code to support this special case. It's also possible that certain things could not be completely reconstructed.

**Comment by AleksMat** [comment] 2021-06-15 19:41
This has now been released in version `3.3.1`.

**Closed by AleksMat** 2021-06-15 19:41 UTC
Labels: enhancement, help wanted
