### ISSUE TITLE
Segfault on import 

### ISSUE THREAD

**Issue by Thingus** [sentinel-hub/sentinelhub-py#73] opened 2019-07-04 13:13 UTC
Hi maintainers

On AWS-hosted Ubuntu 18.04 server,

```python
import sentinelhub
```
fails with a segfault.
On strace, something seems to be repeatedly opening and closing the same file:
```
openat(AT_FDCWD, "/home/ubuntu/tools/miniconda/envs/pyeo_env/share/proj/epsg", O_RDONLY) = 6
close(6)
```
Using sentinelhub in a conda environment, installed with pip. Python 3.7.3, numpy 1.16.4 - everything else as installed in the pip. I'll put my whole environment in the first comment.

Thanks,

**Comment by Thingus** [comment] 2019-07-04 13:14
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl
boto3                     1.9.35                    <pip>
botocore                  1.12.35                   <pip>
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.14.12              h8948797_3
certifi                   2019.6.16                py37_0    conda-forge
chardet                   3.0.4                     <pip>
Click                     7.0                       <pip>
curl                      7.61.0               h84994c4_0
Cython                    0.29                      <pip>
docutils                  0.14                      <pip>
expat                     2.2.6                he6710b0_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
freexl                    1.0.5                h14c3975_0
gdal                      2.3.0            py37h04863e7_1
geojson                   2.4.1                     <pip>
geomet                    0.2.0.post2               <pip>
geos                      3.6.2                heeff764_2
giflib                    5.1.4                h14c3975_1
glib                      2.56.2               hd408876_0
hdf4                      4.2.13               h3ca952b_2
hdf5                      1.8.18               h6792536_1
html2text                 2018.1.9                  <pip>
icu                       58.2                 h9c2bf20_1
idna                      2.7                       <pip>
intel-openmp              2019.0                      118
jmespath                  0.9.3                     <pip>
joblib                    0.12.5                   py37_0
jpeg                      9b                   h024ee3a_2
json-c                    0.13.1               h1bed415_0
kealib                    1.4.7                h5472223_5
krb5                      1.16.1               hc83ff2d_6
libblas                   3.8.0                    10_mkl    conda-forge
libboost                  1.67.0               h46d08c1_4
libcblas                  3.8.0                    10_mkl    conda-forge
libcurl                   7.61.0               h1ad7b7a_0
libdap4                   3.19.1               h6ec2957_0
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgdal                   2.3.0                heea9cce_1
libgfortran-ng            7.3.0                hdf63c60_0
libkml                    1.3.0                h590aaf7_4
liblapack                 3.8.0                    10_mkl    conda-forge
libnetcdf                 4.6.1                h015f1c5_0
libpng                    1.6.35               hbc83047_0
libpq                     10.5                 h1ad7b7a_0
libspatialite             4.3.0a              he475c7f_19
libssh2                   1.8.0                h9cfc8f7_4
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.9                he85c1e1_2
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.8                h26e45fe_1
mkl                       2019.0                      118
mkl_fft                   1.0.6            py37h7dd41cf_0
mkl_random                1.0.1            py37h4414c95_1
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
numpy-base                1.15.3           py37h81de0dd_0
openjpeg                  2.3.0                h05c96fa_1
openssl                   1.1.1b               h14c3975_1    conda-forge
pcre                      8.42                 h439df22_0
Pillow                    5.3.0                     <pip>
pip                       19.1.1                   py37_0    conda-forge
pixman                    0.34.0               hceecf20_3
poppler                   0.65.0               h581218d_1
poppler-data              0.4.9                         0
proj4                     5.0.1                h14c3975_0
pyproj                    1.9.5.1                   <pip>
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.7.5                     <pip>
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.20.0                    <pip>
s3transfer                0.1.13                    <pip>
scikit-learn              0.20.0           py37h4989274_1
scipy                     1.1.0            py37hfa4b5c9_1
sentinelhub               2.4.4                     <pip>
sentinelsat               0.12.2                    <pip>
setuptools                41.0.1                   py37_0    conda-forge
Shapely                   1.6.4.post2               <pip>
six                       1.11.0                    <pip>
sqlite                    3.28.0               hcee41ef_1    conda-forge
tenacity                  5.0.2                     <pip>
tifffile                  2018.10.18                <pip>
tk                        8.6.9             hed695b0_1002    conda-forge
tqdm                      4.28.1                    <pip>
urllib3                   1.24                      <pip>
utm                       0.4.2                     <pip>
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2                h780794e_0
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

**Comment by panisson** [comment] 2019-07-05 17:54
Same here, segmentation fault in similar environment (sentinelhub + conda env) when importing sentinelhub.

After some debugging, I've found something that might help.
Commenting the call at line 265 of sentinelhub/areas.py (changed `POP_WEB_MAX = transform_point((180, 0), CRS.WGS84, CRS.POP_WEB)[0]` to `POP_WEB_MAX = None`) the import works without a segmentation fault.

@Thingus can you check if commenting this call the import works also for you?

**Comment by Thingus** [comment] 2019-07-08 08:37
@panisson Thanks - that fixed the import. From your patch and my trace, it might be something to do with the file containing the epsg file - I'll investigate it now and get back to you.

**Comment by Thingus** [comment] 2019-07-08 08:55
Possibly related issue here? https://github.com/pyproj4/pyproj/issues/257

**Comment by Thingus** [comment] 2019-07-08 09:22
On further digging, segfault seems to be occuring on calling the .projection method of the CRS objects referenced in @panisson 's patch.

**Comment by Thingus** [comment] 2019-07-08 12:46
Raised as a new issue: https://github.com/pyproj4/pyproj/issues/367

**Comment by JohnMBrandt** [comment] 2019-07-09 17:41
Also having this issue and @panisson's suggestion fixed the issue temporarily.

**Comment by AleksMat** [comment] 2019-07-29 16:11
Thanks for finding the solution. I added the following fix in the code: https://github.com/sentinel-hub/sentinelhub-py/blob/5f7258936367b4086373a1b79cb6ae5d648c8833/sentinelhub/constants.py#L346
This way `sentinelhub` package stays compatible both with `pyproj` versions 1 and 2.

**Comment by AleksMat** [comment] 2019-07-30 15:47
After looking further into this, the solution is not so easy. 
- The issue is exactly the following: https://github.com/pyproj4/pyproj/issues/368
- Replacing `init=self.ogc_string()` with `self.ogc_string()` or `self.epsg` is not correct. That is because the resulting `Proj` object would have coordinate order lat-lng instead of lng-lat.

For now we will wait for this to be resolved at `pyproj` package.

**Comment by AleksMat** [comment] 2020-02-13 09:53
In the PR https://github.com/sentinel-hub/sentinelhub-py/pull/102 the remaining issues have been fixed. The changes will be released to master on Monday.

**Closed by AleksMat** 2020-02-13 09:53 UTC
Labels: bug
